blogs/urls.py
from django.urls import path
from . import views

app_name = "blogs"

urlpatterns = [
    path('', views.index, name="all"),
]

jobs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from jobs import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name= 'home'),
    path('jobs', include('jobs.urls')),
    path('blogs', include('blogs.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):

    title = models.CharField(max_length = 255)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to = 'images/')

    def __str__(self):
        return self.title;

jobs/models.py
from django.db import models

# Create your models here.
class Job(models.Model):
    image = models.ImageField(upload_to="images/")
    summary = models.CharField(max_length=500)

blogs/views.py
from django.shortcuts import render
from .models import Blog
# Create your views here.

def index(request):
    blogs = Blog.objects.all()
    context = {'blogs':blogs}
    return render(request, 'blogs/index.html', context)

jobs/views.py
from django.shortcuts import render
from .models import *

def home(request):
    jobs = Job.objects.all()
    return render(request, 'jobs/home.html', {'jobs':jobs})

templates/blogs/index.html
<!doctype html>
<html lang="en">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Album example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/album/">

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      .img-container{

      }

      .img-container > img{
        width: 100%;
        height: 100%;
        object-fit: cover;
        object-position: center;
        border-radius: inherit;
      }


      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">AKRAM AKH</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
              <a class="nav-item nav-link" href="#">LinkedIn</a>
              <a class="nav-item nav-link" href="{% static 'resume.pdf' %}">Resume</a>
              <a class="nav-item nav-link" href="{% url 'blogs:all' %}">Blogs</a>
            </div>
          </div>
        </div>

    </nav>
</header>

<main role="main">


  <div class="album py-5 bg-light">
    <div class="container">
      <h1 class="text-center ">Blogs</h1><br><br>
      {% if blogs %}
      <div class="row">
        {% for blog in blogs %}
        <div class="col-md-6">
          <div class="card mb-6 shadow-sm">
            <div class="img-container">
              <img src="{{ blog.image.url }}" alt="">
            </div>
            <div class="card-body">
              <h1 class="card-text">{{ blog.title }}</h1>
              <p class="card-text">{{ blog.body }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Like</button>
                </div>
                <small class="text-muted">{{ blog.pub_date}}</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      {% else %}
      <div class="row">
        <div class="col-md-12 text-center">
          <p>Opps! There is no blogs yet.</p>
        </div>
      </div>
      {% endif %}
    </div>
  </div>

</main>

<footer class="text-muted bg-dark" style="padding: 20px">
  <div class="container ">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p class="float-left">akramakh &copy; {% now "Y" %}</p>
    <p class="text-center">portfolio</p>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/jobs/home.html
<!doctype html>
<html lang="en">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Album example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/album/">

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      .img-container{

      }

      .img-container > img{
        width: 100%;
        height: 100%;
        object-fit: cover;
        object-position: center;
        border-radius: inherit;
      }

      .personal-img{
        margin: auto;
        width: 200px;
        height: 200px;
        border-radius: 50%;
        margin-bottom: 20px;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">AKRAM AKH</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
              <a class="nav-item nav-link" href="#">LinkedIn</a>
              <a class="nav-item nav-link" href="{% static 'resume.pdf' %}">Resume</a>
              <a class="nav-item nav-link" href="{% url 'blogs:all' %}">Blogs</a>
            </div>
          </div>
        </div>

    </nav>
</header>

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <div class="img-container personal-img">
        <img src="{% static 'akram.jpg' %}" alt="">
      </div>
      <h1 class="jumbotron-heading">Hi, I'm Akram</h1>
      <p class="lead text-muted">Creative Web Developer, Software Design, UI/UX Design, Front-End Developer (HTML5, CSS3, JavaScript and VueJS) and Back-End Developer (PHP, Laravel Framework and MySQL).</p>
      <p>
        <a href="mailto:akram.iwork@gmail.com" class="btn btn-primary my-2">Contact</a>
      </p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <h1 class="text-center ">Jobs</h1><br><br>
      {% if jobs %}
      <div class="row">
        {% for job in jobs %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div class="img-container">
              <img src="{{ job.image.url }}" alt="">
            </div>
            <div class="card-body">
              <p class="card-text">{{ job.summary }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Like</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      {% else %}
      <div class="row">
        <div class="col-md-12 text-center">
          <p>Opps! There is no jobs yet.</p>
        </div>
      </div>
      {% endif %}
    </div>
  </div>

</main>

<footer class="text-muted bg-dark" style="padding: 20px">
  <div class="container ">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p class="float-left">akramakh &copy; {% now "Y" %}</p>
    <p class="text-center">portfolio</p>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>